i18n/bot.en-us.yml
i18n/bot.pt-br.yml

Found some typos during translation, so fixed them.
I thought @kindle.com is most common for e-mail addresses, so made that consistent.
Cheers

Fixed some typos and inconsistencies

---

i18n/bot.es-es.yml

I've added the Spanish translation. Maybe some words doesn't make
sense because of the missing context of the sentences.
Fixing #18

Added the Spanish translation

---

i18n/bot.pt-br.yml

Adding some missing accents and portuguese words translate.

Fixing typo in bot.pt-br.yml

---

i18n/bot.id-id.yml

As I write this translation, I notice some typos in the original i18n (en-us)
Probably going to fix them in separate pull request.

Adding the Indonesian Translation

---

i18n/bot.de-de.yml

Hi,
this PR adds a german translation to Send2KindleBot. It is written in the polite way of talking in german 
Cheers 🍺!

Add german translation

---

i18n/bot.hi.yml

Add Hindi translations

---

i18n/bot.nl.yml

Increased quality of dutch translation

---

i18n/bot.tr-tr.yml

Turkish translation.

---

i18n/bot.fr-fr.yml
i18n/bot.fr.yml

As suggested in #15, I've translated the bot into French.
Be careful though, as French is often a little bit more verbose than English, and sometimes sentences have to be longer and can cause problems UI/UX wise :smile:

French translation 

---

i18n/bot.bm-ms.yml

Added Malay Translation

---

i18n/bot.sv-se.yml

Created a new translations file and translated all the strings to Swedish

Translate bot into Swedish

---

i18n/bot.pl

I've seen your tweet that people were adding translations during hacktoberfest. Thought that maybe you need polish one as well so here you go!

Added polish translation file

---

README_KO.md

Added korean translation for README

---

i18n/bot.de.yml

This commit adds german translation for "slowmode" and "slowmodesec" as mentioned as asked for in #79.

updated german translation

---

i18n/bot.ar.yml

Type: Feat
Subject: Translate string slowmodesec to ar language

Translate string slowmodesec to ar language

---

i18n/bot.ar.yml

Type: Feat
Subject: Translate string slowmode to ar language

Translate string slowmode to ar language

---

i18n/bot.id.yml

Type : Feat
Subject: Translate string slowmodesec to id language

Translate string slowmodesec to id language

---

i18n/bot.en-in.yml

Type: Feat
Subject: Translate slowmode to en-in

Translate slowmode to en-in

---

i18n/bot.nl.yml

Type : Feat
Subject : Translate slowmode to nl language

Translate slowmode to nl language

---

i18n/bot.nl.yml

Type: Feat
Subject: Translate string slowmodesec to nl language

Translate string slowmodesec to nl language

---

i18n/bot.ur-en.yml

Type: Feat
Subject: Translate slowmodesec to ur-en language

Translate slowmodesec to ur-en language

---

i18n/bot.ur-en.yml

Type: Feat
Subject: Translate slowmode to ur-en language

Translate slowmode to ur-en language

---

i18n/bot.tr-tr.yml

Type : Feat
Subject: Translate slowmodesec to tr-tr

Translate slowmodesec to tr-tr

---

i18n/bot.tr-tr.yml

Type: Feat
Subject: Translate slowmode to tr-tr

Translate slowmode to tr-tr

---

i18n/bot.kr.yml

Type: Feat
Subject: Translate slowmode to kr language

Translate slowmode to kr language

---

i18n/bot.kr.yml

Type: Feat
Subject: Translate slowmodesec to kr

Translate slowmodesec to kr

---

i18n/bot.ml-in.yml

Type: Feat
Subject: Translate slowmode to ml-IN

Translate slowmode to ml-IN

---

i18n/bot.bm-ms.yml

Type : Feat
Subject: Translate slowmode to bm-ms language

Translate slowmode to bm-ms language

---

i18n/bot.zh-hant-tw.yml

Type: Feat
Subject: Translate slowmode to zh-hant-tw

Translate slowmode to zh-hant-tw
